version: "3.9"

services:
  coremagick:
    image: allumina/coremagick:0.0.2
    container_name: coremagick
    hostname: coremagick
    networks:
      - coremagick
    ports:
      - 8081:80
      - 8441:443
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes: 
      - type: volume
        source: coremagick-data
        target: /data

networks:
  coremagick:

volumes: 
    coremagick-data:
        name: coremagick-data     
        #driver: local
        driver_opts:
            o: bind
            type: none
            device: ./data
        #external: true   
